#!/usr/bin/env bash
set -eu
set -o pipefail

SCRIPT_NAME=`basename $0`
XBOXDRV_DIR=$HOME/home/etc/xboxdrv
STEAM_EXE="$HOME/.wine/drive_c/Program Files/Steam/Steam.exe"

OPT_HELP=
OPT_KILL=
OPT_LIST=
OPT_PROFILE_EXIT=
OPT_PROFILE=base

error () {
  echo -e "\e[0;31m\e[1merror: \e[0;0m$@" >&2
  exit 1
}

mute () {
  $@ > /dev/null 2>&1
}

display_help () {
  cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS] <STEAM_GAME_ID> <PROFILE>
EOF
  exit 0
}

kill_xboxdrv () {
  mute sudo kill $(pgrep -a xboxdrv | awk '{print $1}')
}

device_count () {
  local device_code=$(xboxdrv -L | egrep -q '^no controller detected$'; echo $?)

  if [[ "${device_code}" == 0 ]]; then
      echo 0
  else
    echo $(xboxdrv -L | sed 1,2d | wc -l)
  fi
}

check_devices () {
  local count=$(device_count)

  if [[ "$count" == 0 ]]; then
      error "Please plug-in the controllers, then re-run this program."
  fi
}

instances () {
  pgrep -a xboxdrv | wc -l
}

load_profile () {
  local profile=${1:-$OPT_PROFILE}
  local count=$(device_count)

  for id in $(seq $count); do
    mute sudo xboxdrv --id $((id-1)) \
         --type xbox360 \
         -c $XBOXDRV_DIR/${profile}_${id}.xboxdrv &
  done
}

ps_xboxdrv () {
  pgrep -a xboxdrv
}

exec_options () {
  if [[ -n "$OPT_HELP" ]]; then
      display_help
  fi

  if [[ -n "$OPT_LIST" ]]; then
      ps_xboxdrv
      exit 0
  fi

  if [[ -n "$OPT_KILL" ]]; then
      kill_xboxdrv
      exit 0
  fi

  if [[ -n "$OPT_PROFILE_EXIT" ]]; then
      load_profile "$OPT_PROFILE_EXIT"
      exit 0
  fi
}

check_steam () {
  if [[ -f "$STEAM_EXE" ]]; then
      return 0
  else
    error "Please install Windows Steam, then re-run this program."
  fi
}

check_programs () {
  check_steam
}

check_config () {
  if [[ ! -d $XBOXDRV_DIR ]]; then
      error "Please create an $XBOXDRV_DIR, then re-run this program."
  fi
}

run_steam () {
  WINEDEBUG=-all wine "$STEAM_EXE" $@
}

launch () {
  if [[ $# == 0 || $# == 1 ]]; then
     run_steam ${1:-}
  else
    display_help
  fi
}

main () {
  while getopts ":hkp:P:l" opt; do
    case $opt in
      h) OPT_HELP=true ;;
      k) OPT_KILL=true ;;
      p) OPT_PROFILE_EXIT=${OPTARG} ;;
      P) OPT_PROFILE=${OPTARG} ;;
      l) OPT_LIST=true ;;
      *) return 1 ;;
    esac
  done
  shift $((OPTIND-1))

  exec_options $@
  check_programs
  check_config
  check_devices
  load_profile
  launch $@
}

main $@
