#!/usr/bin/env bash
set -eu
set -o pipefail

XBOXDRV_DIR=$HOME/home/etc/xboxdrv
SCRIPT_NAME=`basename $0`
STEAM_EXE="$HOME/.wine/drive_c/Program Files/Steam/Steam.exe"

OPT_HELP=
OPT_KILL=
OPT_LIST=
OPT_PROFILE=base
OPT_CONTROLLERS=2

error () {
  echo -e "\e[0;31m\e[1merror: \e[0;0m$@" >&2
  exit 1
}

mute () {
  $@ > /dev/null 2>&1
}

display_help () {
  cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS] <STEAM_GAME_ID> <PROFILE>
EOF
  exit 0
}

kill_xboxdrv () {
  mute sudo kill $(pgrep -a xboxdrv | awk '{print $1}')
  exit $?
}

check_devices () {
  local controller_count=$(xboxdrv -L | sed 1,2d | wc -l)
  local controller_code=$(xboxdrv -L | egrep -q '^no controller detected$'; echo $?)

  if [[ ${controller_count} == ${OPT_CONTROLLERS} && \
            ${controller_code} != 0 ]]; then
      return 0
  else
    error "Please plug-in the controllers, then run this program again."
  fi
}

load_xboxdrv () {
  check_devices

  local instance_count=$(pgrep -a xboxdrv | wc -l)
  local profile=${1:-${OPT_PROFILE}}

  if [[ "$instance_count" != ${OPT_CONTROLLERS} ]]; then
      for id in $(seq 2); do
        mute sudo xboxdrv --id $((id-1)) \
             --type xbox360 \
             -c $XBOXDRV_DIR/${profile}_${id}.xboxdrv &
      done
  fi
}

set_options () {
  while getopts ":hkp:lc:" opt; do
    case $opt in
      h) OPT_HELP=true ;;
      k) OPT_KILL=true ;;
      p) OPT_PROFILE=${OPTARG} ;;
      l) OPT_LIST=true ;;
      c) OPT_CONTROLLERS=${OPTARG} ;;
      *) return 1 ;;
    esac
  done

  shift $((OPTIND-1))

}

ps_xboxdrv () {
  pgrep -a xboxdrv
}

exec_options () {
  if [[ -n "$OPT_HELP" ]]; then
      display_help
  fi

  if [[ -n "$OPT_LIST" ]]; then
      ps_xboxdrv
      exit 0
  fi

  if [[ -n "$OPT_KILL" ]]; then
      kill_xboxdrv
  fi

  if [[ -n "$OPT_PROFILE" ]]; then
      load_xboxdrv
      exit 0
  fi
}

check_steam () {
  if [[ -f "$STEAM_EXE" ]]; then
      return 0
  else
    return 1
  fi
}

run_steam () {
  WINEDEBUG=-all wine $STEAM_EXE $@
}

launch () {
  if [[ $# -ge 0 && $# < 3 ]]; then
      run_steam ${1:-}
  else
    display_help
  fi
}

main () {
  if check_steam; then
      set_options $@
      exec_options
      load_xboxdrv ${2:-}
      launch $@
  else
    error "Please install Windows Steam, then re-run this program"
  fi
}

main $@
